#Script that runs all program tests

require 'test/unit'
require_relative 'TestAgeYear'
require_relative 'TestExpense'
require_relative 'TestIncome'
require_relative 'TestIncomeTax'
require_relative 'TestIRA'
require_relative 'Testnon-IRA'
require_relative 'TestResultsYear'
require_relative 'TestResultsAge'
require_relative 'TestMoneyRanOut'
require_relative 'TestLastYearWithMoney'
require_relative 'TestCsvResults'
require_relative 'TestConfig'
